/**
 * Unit tests for perturbation calculations.
 *
 * Expected values come straight from `tests/perturbation_test_data.json`,
 * which is generated by `tests/simple_perturbation_calc.py`. The fixture used
 * to be duplicated inline here, which let the reference implementation and the
 * assertions drift apart — importing it keeps generator, fixture and test in
 * one chain. Test files are excluded from `tsc -b` (see the `exclude` glob in
 * `tsconfig.json`) and Bun resolves JSON imports natively, so this needs no
 * `resolveJsonModule`.
 */

import {
  atmosphericScaleHeightKm,
  calculateAtmosphericDensity,
  calculateDetailedPerturbationRates,
  formatJ2PerturbationRates,
  formatJ3PerturbationRates,
} from './perturbation';
import testData from '../../tests/perturbation_test_data.json';

const MU = 3.986004418e14; // m^3/s^2, matching perturbation.ts
const EARTH_RADIUS_M = 6378137.0;
const SECONDS_PER_YEAR = 365.25 * 24 * 3600;


describe('Perturbation calculations', () => {
  testData.forEach((testCase) => {
    describe(testCase.name, () => {
      const result = calculateDetailedPerturbationRates(testCase.input);
      
      it('should calculate J2 perturbations correctly', () => {
        const DAYS_PER_YEAR = 365.25;
        
        // Convert our year-based results to day-based for comparison
        const actualJ2DegPerDay = {
          dOmega_dt: result.j2.dOmega_dt / DAYS_PER_YEAR,
          domega_dt: result.j2.domega_dt / DAYS_PER_YEAR,
        };
        
        expect(actualJ2DegPerDay.dOmega_dt).toBeCloseTo(
          testCase.expected.j2.dOmega_dt_deg_per_day, 
          6
        );
        expect(actualJ2DegPerDay.domega_dt).toBeCloseTo(
          testCase.expected.j2.domega_dt_deg_per_day, 
          6
        );
      });
      
      it('should calculate J3 perturbations correctly', () => {
        expect(result.j3.de_dt).toBeCloseTo(
          testCase.expected.j3.de_dt_per_year, 
          10
        );
        expect(result.j3.di_dt).toBeCloseTo(
          testCase.expected.j3.di_dt_deg_per_year, 
          6
        );
        expect(result.j3.dOmega_dt).toBeCloseTo(
          testCase.expected.j3.dOmega_dt_deg_per_year, 
          6
        );
        expect(result.j3.domega_dt).toBeCloseTo(
          testCase.expected.j3.domega_dt_deg_per_year, 
          6
        );
      });
      
      it('should calculate drag perturbations correctly', () => {
        // Relative comparison: da/dt spans -22 km/yr (LEO) to exactly 0 (GEO,
        // Molniya — both gated out by lowOrbitLimitKm), so a fixed number of
        // decimal places would be meaningless at one end or the other.
        const expectedDa = testCase.expected.drag.da_dt_km_per_year;
        const expectedDe = testCase.expected.drag.de_dt_per_year;

        if (expectedDa === 0) {
          expect(result.drag.da_dt).toBe(0);
          expect(result.drag.de_dt).toBe(0);
        } else {
          expect(result.drag.da_dt / expectedDa).toBeCloseTo(1, 9);
          expect(result.drag.de_dt / expectedDe).toBeCloseTo(1, 9);
        }
      });

      it('should have zero values for non-affected elements', () => {
        // J2 doesn't affect a, e, i (first order)
        expect(result.j2.da_dt).toBe(0);
        expect(result.j2.de_dt).toBe(0);
        expect(result.j2.di_dt).toBe(0);

        // J3 doesn't affect a (first order)
        expect(result.j3.da_dt).toBe(0);
        expect(result.j3.dM_dt).toBe(0);

        // Drag doesn't affect i, RAAN or argument of perigee
        expect(result.drag.di_dt).toBe(0);
        expect(result.drag.dOmega_dt).toBe(0);
        expect(result.drag.domega_dt).toBe(0);
      });
    });
  });
  
  describe('Formatting functions', () => {
    const sampleRates = {
      da_dt: 0,
      de_dt: 1.5e-6,
      di_dt: -0.67,
      dOmega_dt: -1827.857,  // deg/year
      domega_dt: 1365.730,   // deg/year
      dM_dt: 0,
    };
    
    it('should format J2 rates with correct units and precision', () => {
      const formatted = formatJ2PerturbationRates(sampleRates);
      expect(formatted).toHaveLength(2); // Should only include non-zero values
      expect(formatted[0].latex).toBe('d\\Omega/dt');
      expect(formatted[0].value).toBe('-5.00 deg/day');
      expect(formatted[1].latex).toBe('d\\omega/dt');
      expect(formatted[1].value).toBe('3.74 deg/day');
    });
    
    it('should format J3 rates with correct units and precision', () => {
      const formatted = formatJ3PerturbationRates(sampleRates);
      expect(formatted).toHaveLength(4);
      expect(formatted.find(f => f.latex === 'de/dt')?.value).toBe('1.50e-6 /year');
      expect(formatted.find(f => f.latex === 'di/dt')?.value).toBe('-0.67 deg/year');
      expect(formatted.find(f => f.latex === 'd\\Omega/dt')?.value).toBe('-1827.86 deg/year');
      expect(formatted.find(f => f.latex === 'd\\omega/dt')?.value).toBe('1365.73 deg/year');
    });
    
    it('should filter out zero values', () => {
      const zeroRates = {
        da_dt: 0,
        de_dt: 0,
        di_dt: 0,
        dOmega_dt: 0,
        domega_dt: 0,
        dM_dt: 0,
      };
      
      expect(formatJ2PerturbationRates(zeroRates)).toHaveLength(0);
      expect(formatJ3PerturbationRates(zeroRates)).toHaveLength(0);
    });
  });
  
  describe('Edge cases', () => {
    it('should handle zero eccentricity', () => {
      const result = calculateDetailedPerturbationRates({
        semiMajorAxisKm: 7000,
        eccentricity: 0,
        inclinationDeg: 45,
        raanDeg: 0,
        argPerigeeDeg: 0,
        meanAnomalyDeg: 0,
      });
      
      expect(result.j2.dOmega_dt).not.toBeNaN();
      expect(result.j2.domega_dt).not.toBeNaN();
      expect(result.j3.de_dt).not.toBeNaN();
    });
    
    it('should handle critical inclination (63.4 degrees)', () => {
      const result = calculateDetailedPerturbationRates({
        semiMajorAxisKm: 7000,
        eccentricity: 0.01,
        inclinationDeg: 63.4,
        raanDeg: 0,
        argPerigeeDeg: 0,
        meanAnomalyDeg: 0,
      });
      
      // At critical inclination, J2 omega perturbation should be very small
      expect(Math.abs(result.j2.domega_dt)).toBeLessThan(10); // deg/year
    });
    
    it('should handle polar orbit', () => {
      const result = calculateDetailedPerturbationRates({
        semiMajorAxisKm: 7000,
        eccentricity: 0.01,
        inclinationDeg: 90,
        raanDeg: 0,
        argPerigeeDeg: 0,
        meanAnomalyDeg: 0,
      });
      
      expect(result.j2.dOmega_dt).toBeCloseTo(0, 1); // Should be ~0 for polar orbit
      expect(result.j3.dOmega_dt).not.toBeNaN();
    });
  });

  /**
   * These pin the drag magnitude, which nothing used to check. `drag.da_dt`
   * had been a factor of the orbital velocity (~7.6e3) too large because `F`
   * was built from `v_rel^2` (an acceleration) where the `-2aF` form needs
   * `v_rel` (a rate); the Harris-Priester path partly hid it behind a
   * `HP_BASE_SCALE = 0.0003` density factor. Both are asserted here so
   * neither can come back unnoticed.
   */
  describe('Atmospheric drag', () => {
    const circularElements = (altitudeKm: number) => ({
      semiMajorAxisKm: (EARTH_RADIUS_M + altitudeKm * 1000) / 1000,
      eccentricity: 0,
      inclinationDeg: 51.6,
      raanDeg: 0,
      argPerigeeDeg: 0,
      meanAnomalyDeg: 0,
    });

    /** Textbook circular-orbit secular decay, km/year. */
    const closedFormDaDt = (altitudeKm: number, ballisticCoefficient: number, model: 'exponential' | 'harris-priester') => {
      const a = EARTH_RADIUS_M + altitudeKm * 1000;
      const rho = calculateAtmosphericDensity(altitudeKm, { model, f107: 150, ap: 15, diurnalBulgeFactor: 0.5 });
      return (-rho * ballisticCoefficient * Math.sqrt(MU * a) * SECONDS_PER_YEAR) / 1000;
    };

    it.each([
      [300, 0.01],
      [550, 0.022],
      [800, 0.05],
      [999, 0.005],
    ])('matches -rho*B*sqrt(mu*a) for a circular orbit at %i km (B=%f)', (altitudeKm, ballisticCoefficient) => {
      for (const model of ['exponential', 'harris-priester'] as const) {
        const result = calculateDetailedPerturbationRates(
          circularElements(altitudeKm),
          ballisticCoefficient,
          { model, f107: 150, ap: 15, diurnalBulgeFactor: 0.5 },
        );
        const expected = closedFormDaDt(altitudeKm, ballisticCoefficient, model);
        expect(expected).toBeLessThan(0);
        expect(result.drag.da_dt / expected).toBeCloseTo(1, 9);
      }
    });

    it('scales da/dt linearly with the ballistic coefficient', () => {
      const single = calculateDetailedPerturbationRates(circularElements(500), 0.01);
      const double = calculateDetailedPerturbationRates(circularElements(500), 0.02);
      expect(double.drag.da_dt / single.drag.da_dt).toBeCloseTo(2, 9);
    });

    it('applies no drag above lowOrbitLimitKm', () => {
      const belowLimit = calculateDetailedPerturbationRates(circularElements(900), 0.02, { lowOrbitLimitKm: 1000 });
      const aboveLimit = calculateDetailedPerturbationRates(circularElements(1100), 0.02, { lowOrbitLimitKm: 1000 });

      expect(belowLimit.drag.da_dt).toBeLessThan(0);
      expect(aboveLimit.drag.da_dt).toBe(0);
      expect(aboveLimit.drag.de_dt).toBe(0);
    });

    describe('eccentricity decay (King-Hele small-e limit)', () => {
      const eccentricElements = (eccentricity: number) => ({
        ...circularElements(550),
        eccentricity,
      });

      it('is exactly zero for a circular orbit', () => {
        // Math.abs normalises the -0 that falls out of (negative da/dt) * 0.
        expect(Math.abs(calculateDetailedPerturbationRates(eccentricElements(0), 0.022).drag.de_dt)).toBe(0);
      });

      it('equals da/dt * e / (2H)', () => {
        for (const model of ['exponential', 'harris-priester'] as const) {
          const atmosphere = { model, f107: 150, ap: 15, diurnalBulgeFactor: 0.5 };
          const eccentricity = 0.002;
          const result = calculateDetailedPerturbationRates(eccentricElements(eccentricity), 0.022, atmosphere);

          // Density (and therefore H) is sampled at perigee, not at the mean altitude.
          const a = EARTH_RADIUS_M + 550 * 1000;
          const perigeeAltitudeKm = (a * (1 - eccentricity) - EARTH_RADIUS_M) / 1000;
          const scaleHeightKm = atmosphericScaleHeightKm(perigeeAltitudeKm, atmosphere);

          // da_dt is km/year and de_dt is 1/year, so the km cancels against H in km.
          const expected = (result.drag.da_dt * eccentricity) / (2 * scaleHeightKm);
          expect(result.drag.de_dt / expected).toBeCloseTo(1, 9);
        }
      });

      it('circularises the orbit rather than growing eccentricity', () => {
        const result = calculateDetailedPerturbationRates(eccentricElements(0.01), 0.022);
        expect(result.drag.de_dt).toBeLessThan(0);
        // Sanity on magnitude: e must not change by more than itself in a year.
        expect(Math.abs(result.drag.de_dt)).toBeLessThan(0.01);
      });
    });

    describe('scale height', () => {
      it('returns the configured value for the exponential model', () => {
        expect(atmosphericScaleHeightKm(550, { model: 'exponential', scaleHeightKm: 45 })).toBe(45);
      });

      it('derives a plausible thermospheric value from the Harris-Priester table', () => {
        for (const altitudeKm of [200, 400, 550, 700]) {
          const scaleHeightKm = atmosphericScaleHeightKm(altitudeKm, { model: 'harris-priester' });
          expect(scaleHeightKm).toBeGreaterThan(20);
          expect(scaleHeightKm).toBeLessThan(150);
        }
      });

      it('stays finite and positive outside the table bounds', () => {
        for (const altitudeKm of [50, 100, 2000, 5000]) {
          const scaleHeightKm = atmosphericScaleHeightKm(altitudeKm, { model: 'harris-priester' });
          expect(Number.isFinite(scaleHeightKm)).toBe(true);
          expect(scaleHeightKm).toBeGreaterThanOrEqual(1);
        }
      });
    });

    /**
     * Regression guard for `HP_BASE_SCALE`. The table value at 550 km is
     * ~6e-13 kg/m^3; the removed 0.0003 factor pushed it to ~2e-16, which is
     * physically absurd for LEO. Bounds are deliberately loose — this catches
     * a reintroduced blanket scale factor, not a density-model refinement.
     */
    it('returns a physically plausible Harris-Priester density in LEO', () => {
      const density550 = calculateAtmosphericDensity(550, { model: 'harris-priester', f107: 150, ap: 15 });
      expect(density550).toBeGreaterThan(1e-14);
      expect(density550).toBeLessThan(1e-11);
    });

    /**
     * Order-of-magnitude anchor only. The ISS loses roughly 2 km/month at
     * ~410 km under moderate solar activity; its ballistic coefficient varies
     * by about 2x with attitude, and the two atmosphere models here bracket
     * the truth from either side, so this is a wide band on purpose.
     */
    it('reproduces ISS-class decay to within an order of magnitude', () => {
      for (const model of ['exponential', 'harris-priester'] as const) {
        const result = calculateDetailedPerturbationRates(circularElements(410), 0.008, {
          model,
          f107: 150,
          ap: 15,
          diurnalBulgeFactor: 0.5,
        });
        const kmPerMonth = -result.drag.da_dt / 12;
        expect(kmPerMonth).toBeGreaterThan(0.2);
        expect(kmPerMonth).toBeLessThan(20);
      }
    });
  });
});